name: Build & Deploy Leading Schools Spring app CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Leading Schools app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build Leading Schools application
        run: |
          mvn clean
          mvn -B package --file pom.xml

  deploy:
    name: Deploy Leading Schools app
    runs-on: ubuntu-latest
    needs: build
    # Add deployment steps here, such as deploying to a cloud platform or server
    steps:
      - name: Deployment Step
        run: echo "Deployment step goes here"
